### ISSUE TITLE
無法做到Firebase Database + Chat Session

### ISSUE THREAD

**Issue by haocheng1029** [kkdai/linebot-cf-firebase#1]
您好，參照您 https://www.evanlin.com/linebot-cloudfunc-firebase-gemini-workshop2/
Realtime Database 有設定OK，BwAI服務帳戶建立OK，在Line Bot 輸入資料後有寫入到Firebase 
GOOGLE_APPLICATION_CREDENTIALS OK
但是GeminiPro還是回覆以下訊息，需要再檢查什麼地方嗎？
由於我是大型語言模型，我沒有個人記憶或互動記錄，因此無法記住你的名字。

**Comment by kkdai** [comment]
![image](https://github.com/kkdai/linebot-cf-firebase/assets/2252691/a0c05e0b-70b2-4d6f-8cef-eddac74fe071)

看起來原因有幾個:

- 重複資料 (先修掉這個)
- 可能是 temproture 設定，

**Comment by kkdai** [comment]
<img width="503" alt="image" src="https://github.com/kkdai/linebot-cf-firebase/assets/2252691/66cc600d-eb22-4cb6-9b17-811cf476fe7a">

<img width="509" alt="image" src="https://github.com/kkdai/linebot-cf-firebase/assets/2252691/03e1d75f-5213-41ab-85d6-e836f1896dba">

**Comment by kkdai** [comment]
先修掉重複記憶造成混亂

**Comment by kkdai** [comment]
我先關起來你測試看看，還有問題可以再來詢問。
